name:                lsh-kdtree-exp
version:             0.1.0.0
synopsis:            Locality Sensitivity Hashing
#description:
homepage:            https://github.com/jproyo/upc-miri/adm/homeworks/homework3#readme
license:             BSD3
author:              Juan Pablo Royo Sales
maintainer:          juanpablo.royo@gmail.com
copyright:           2020 Juan Pablo Royo Sales
category:            Experimental
extra-source-files:
- README.md

dependencies:
  - base

default-extensions:
  - OverloadedStrings

library:
  exposed-modules:
    - Data.LSH.LSH
    - Data.Tree.KDTree
    - Experiments

  source-dirs:
    - src

  ghc-options:
    - -Wall
    - -fconstraint-solver-iterations=0
    - -fno-warn-orphans
    - -fno-warn-partial-type-signatures
    - -O2
    - -Werror
    - -fdiagnostics-color=always

  dependencies:
    - base
    - containers
    - deepseq
    - hashable
    - random
    - split
    - text
    - time
    - QuickCheck

executables:
  lsh-kdtree-bench:
    main: Main.hs
    source-dirs: app/bench
    dependencies:
      - lsh-kdtree-exp
      - criterion

  lsh-kdtree-data:
    main: Main.hs
    source-dirs: app/data
    dependencies:
      - directory
      - lsh-kdtree-exp
      - text
      - time

tests:
  random-bst-test:
    main: Spec.hs
    source-dirs:
      - test
      - src
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
      - -fdiagnostics-color=always
    dependencies:
      - QuickCheck
