name:                random-bst
version:             0.1.0.0
synopsis:            A Random Build Binary Search Tree
#description:
homepage:            https://github.com/jproyo/upc-miri/ads/homeworks/homework1/random-bst#readme
license:             BSD3
author:              Juan Pablo Royo Sales
maintainer:          juanpablo.royo@gmail.com
copyright:           2020 Juan Pablo Royo Sales
category:            Experimental
extra-source-files:
- README.md

library:
  exposed-modules:
    - RandomBST

  source-dirs:
    - src

  ghc-options:
    - -Wall
    - -fconstraint-solver-iterations=0
    - -fno-warn-orphans
    - -fno-warn-partial-type-signatures
    - -O2
    - -Werror
    - -fdiagnostics-color=always

  dependencies:
    - base
    - containers
    - directory
    - pretty-simple
    - random
    - time

tests:
  random-bst-test:
    main: Spec.hs
    source-dirs:
      - test
      - src
    ghc-options:
      - -threaded
      - -O2
      - -rtsopts
      - -with-rtsopts=-N
      - -fdiagnostics-color=always
    dependencies:
      - base
      - QuickCheck
      - test-framework
      - test-framework-quickcheck2
